title: Dr. Julie Griffin
base_url:  https://samjgriffin89.github.io/drjuliegriffin.com/
email: anemail@gmail.com
phone_number: 123-234-1231
address: "8471 Turnpike Drive, Westminster, CO 80031"
description: > #
  Dr. Julie Melowsky Griffin, PsyD obtained her doctoral degree in Psychology from the University of Denver in 2017. 
  She specializes in individual therapy with teens and adults, couples and family therapy. Julie provides animal assisted therapy with her 
  certfiied therapy dog, Lexie Waffles.

google_analytics_id: 
google_site_verification: 
google_maps_api_key: AIzaSyC4DHSne1itZ1-MkC6PMDZwWvxeHgFttQc

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - .gitignore
  - README.md