title: Sam Griffin
base_url: samjgriffin.com
email: samjgriffin89@gmail.com
description: > #
  I am Sam Griffin, a full stack developer currently working at Cardfree,building out RESTful services that supports our mobile apps and customer portal. 
  For the most part I am working in .NET using Web API, but am becoming more immersed in RoR and grails.

google_analytics_id: UA-24433484-1
google_site_verification: cT3CHL7PrHfUex3GIuLkyjnk-deuZyedUYGqJGOKGEc

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - .gitignore
  - README.md