title: Dr. Julie Griffin
base_url:  https://samjgriffin89.github.io/drjuliegriffin.com/
#base_url:  http://localhost:4000
email: juliemelowsky@gmail.com
description: > #
  Dr. Julie Griffin is ....

google_analytics_id: 
google_site_verification: 
google_maps_api_key: AIzaSyC4DHSne1itZ1-MkC6PMDZwWvxeHgFttQc

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - .gitignore
  - README.md